spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/test
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: gptRecommendation01
server:
  port: 8080

